In [67]:
import pandas as pd
from sklearn.preprocessing import KBinsDiscretizer, OrdinalEncoder

In [68]:
df = pd.read_pickle("../data/skin-lesion-data/binary.pickle")

In [69]:
df.describe(include="all")

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed,malignant
count,773,773.000000,773,773,773,773,773.000000,773,773,773,...,773,773,773,773,773,773,773,773,773,773
unique,539,NaN,2,2,10,11,NaN,2,2,2,...,6,2,2,2,2,2,2,773,2,2
top,PAT_645,NaN,False,False,POMERANIA,POMERANIA,NaN,False,FEMALE,False,...,BCC,True,True,False,False,False,True,PAT_46_881_939.png,True,True
freq,8,NaN,674,587,280,282,NaN,454,396,420,...,392,551,442,576,673,488,533,1,657,491
mean,NaN,1148.250970,NaN,NaN,NaN,NaN,63.932730,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,872.146016,NaN,NaN,NaN,NaN,14.101616,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,17.000000,NaN,NaN,NaN,NaN,14.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,440.000000,NaN,NaN,NaN,NaN,55.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1009.000000,NaN,NaN,NaN,NaN,64.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1519.000000,NaN,NaN,NaN,NaN,74.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,4734.000000,NaN,NaN,NaN,NaN,94.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Drop irrelevant features

In [70]:
df = df.drop("patient_id", axis=1)
df = df.drop("lesion_id", axis=1)
df = df.drop("img_id", axis=1)
df

,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,biopsed,malignant
1,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,True,True,...,5.0,BCC,True,True,False,True,True,True,True,True
4,False,True,POMERANIA,POMERANIA,79,False,MALE,True,False,False,...,5.0,BCC,True,True,False,False,True,True,True,True
6,False,True,GERMANY,ITALY,52,False,FEMALE,False,True,True,...,10.0,BCC,False,True,False,True,True,True,True,True
7,False,False,POMERANIA,POMERANIA,74,True,FEMALE,False,False,False,...,10.0,BCC,True,True,True,False,True,True,True,True
9,False,True,GERMANY,GERMANY,58,True,FEMALE,True,True,True,...,7.0,ACK,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,False,False,POMERANIA,POMERANIA,61,True,MALE,False,True,True,...,9.0,BCC,True,True,True,False,True,False,True,True
2284,False,True,POMERANIA,POMERANIA,60,True,FEMALE,True,False,False,...,2.0,ACK,False,False,False,False,False,False,True,False
2286,False,False,UNK,ITALY,20,True,FEMALE,False,False,False,...,2.0,ACK,False,False,False,False,False,True,True,False
2287,False,False,ITALY,GERMANY,75,False,MALE,True,False,True,...,34.0,MEL,False,True,False,False,False,False,True,True
2289,True,False,POMERANIA,POMERANIA,66,False,MALE,True,False,True,...,15.0,ACK,True,False,True,False,True,True,True,False

In [71]:
df.select_dtypes(include=["int", "float"]).columns

Index(['age', 'fitspatrick', 'diameter_1', 'diameter_2'], dtype='object')

# Binning

## Age 3 bins

1. Young
2. Adult
3. Elderly

In [72]:
labels = ["young", "adult", "elderly"]
discretizer = KBinsDiscretizer(n_bins=len(labels), encode="ordinal", strategy="uniform")
df["age"] = discretizer.fit_transform(df[["age"]]).astype(int)
df["age"]

1       1
4       2
6       1
7       2
9       1
       ..
2275    1
2284    1
2286    0
2287    2
2289    1
Name: age, Length: 773, dtype: int64

## Fitspatrick 6 bins

1. I
2. II
3. III
4. IV
5. V
6. VI

In [73]:
df["fitspatrick"].unique()

array([3., 1., 2., 4., 5., 6.])

In [74]:
df["fitspatrick"] = df["fitspatrick"].astype(int)
df["fitspatrick"]

1       3
4       1
6       3
7       1
9       1
       ..
2275    2
2284    2
2286    4
2287    2
2289    2
Name: fitspatrick, Length: 773, dtype: int64

## Diameter 3 bins

1. Short
2. Medium
3. Long

In [75]:
labels = ["short", "medium", "long"]

In [76]:
discretizer = KBinsDiscretizer(n_bins=len(labels), encode="ordinal", strategy="uniform")
df["diameter_1"] = discretizer.fit_transform(df[["diameter_1"]]).astype(int)
df["diameter_1"]

1       0
4       0
6       0
7       0
9       0
       ..
2275    0
2284    0
2286    0
2287    1
2289    0
Name: diameter_1, Length: 773, dtype: int64

In [54]:
discretizer = KBinsDiscretizer(n_bins=len(labels), encode="ordinal", strategy="uniform")
df["diameter_2"] = discretizer.fit_transform(df[["diameter_2"]]).astype(int)
df["diameter_2"]

1       0
4       0
6       0
7       0
9       0
       ..
2275    0
2284    0
2286    0
2287    1
2289    0
Name: diameter_2, Length: 773, dtype: int64

In [55]:
df.select_dtypes(include=["float"]).columns

Index([], dtype='object')

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 773 entries, 1 to 2289
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   smoke                773 non-null    boolean
 1   drink                773 non-null    boolean
 2   background_father    773 non-null    category
 3   background_mother    773 non-null    category
 4   age                  773 non-null    int64
 5   pesticide            773 non-null    boolean
 6   gender               773 non-null    category
 7   skin_cancer_history  773 non-null    boolean
 8   cancer_history       773 non-null    boolean
 9   has_piped_water      773 non-null    boolean
 10  has_sewage_system    773 non-null    boolean
 11  fitspatrick          773 non-null    int64
 12  region               773 non-null    category
 13  diameter_1           773 non-null    int64
 14  diameter_2           773 non-null    int64
 15  diagnostic           773 non-null    category
 16  itch                 773 non-null    boolean
 17  grew                 773 non-null    boolean
 18  hurt                 773 non-null    boolean
 19  changed              773 non-null    boolean
 20  bleed                773 non-null    boolean
 21  elevation            773 non-null    boolean
 22  biopsed              773 non-null    bool
 23  malignant            773 non-null    bool
dtypes: bool(2), boolean(13), category(5), int64(4)
memory usage: 56.9 KB

In [57]:
df.describe(include="all")

,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,biopsed,malignant
count,773,773,773,773,773.000000,773,773,773,773,773,...,773.000000,773,773,773,773,773,773,773,773,773
unique,2,2,10,11,NaN,2,2,2,2,2,...,NaN,6,2,2,2,2,2,2,2,2
top,False,False,POMERANIA,POMERANIA,NaN,False,FEMALE,False,True,True,...,NaN,BCC,True,True,False,False,False,True,True,True
freq,674,587,280,282,NaN,454,396,420,419,454,...,NaN,392,551,442,576,673,488,533,657,491
mean,NaN,NaN,NaN,NaN,1.376455,NaN,NaN,NaN,NaN,NaN,...,0.042691,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,0.592976,NaN,NaN,NaN,NaN,NaN,...,0.220666,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,...,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df.select_dtypes(include=["category"]).columns

Index(['background_father', 'background_mother', 'gender', 'region',
       'diagnostic'],
      dtype='object')

# Ordinal Encoding

## Backgrounds

In [ ]:
ordinal_encoder = OrdinalEncoder()
df["background_father"] = ordinal_encoder.fit_transform(df[["background_father"]]).astype(int)
df["background_father"]

1       7
4       7
6       2
7       7
9       2
       ..
2275    7
2284    7
2286    9
2287    4
2289    7
Name: background_father, Length: 773, dtype: int64

In [60]:
ordinal_encoder = OrdinalEncoder()
df["background_mother"] = ordinal_encoder.fit_transform(df[["background_mother"]]).astype(int)
df["background_mother"]

1       7
4       7
6       3
7       7
9       2
       ..
2275    7
2284    7
2286    3
2287    2
2289    7
Name: background_mother, Length: 773, dtype: int64

## Gender

In [61]:
ordinal_encoder = OrdinalEncoder()
df["gender"] = ordinal_encoder.fit_transform(df[["gender"]]).astype(int)
df["gender"]

1       0
4       1
6       0
7       0
9       0
       ..
2275    1
2284    0
2286    0
2287    1
2289    1
Name: gender, Length: 773, dtype: int64

## Region

In [62]:
ordinal_encoder = OrdinalEncoder()
df["region"] = ordinal_encoder.fit_transform(df[["region"]]).astype(int)
df["region"]

1       10
4        7
6        5
7        5
9        7
        ..
2275     7
2284     5
2286     2
2287     7
2289     4
Name: region, Length: 773, dtype: int64

## Diagnostic

In [63]:
ordinal_encoder = OrdinalEncoder()
df["diagnostic"] = ordinal_encoder.fit_transform(df[["diagnostic"]]).astype(int)
df["diagnostic"]

1       1
4       1
6       1
7       1
9       0
       ..
2275    1
2284    0
2286    0
2287    2
2289    0
Name: diagnostic, Length: 773, dtype: int64

In [64]:
df.select_dtypes(include=["category"]).columns

Index([], dtype='object')

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 773 entries, 1 to 2289
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   smoke                773 non-null    boolean
 1   drink                773 non-null    boolean
 2   background_father    773 non-null    int64
 3   background_mother    773 non-null    int64
 4   age                  773 non-null    int64
 5   pesticide            773 non-null    boolean
 6   gender               773 non-null    int64
 7   skin_cancer_history  773 non-null    boolean
 8   cancer_history       773 non-null    boolean
 9   has_piped_water      773 non-null    boolean
 10  has_sewage_system    773 non-null    boolean
 11  fitspatrick          773 non-null    int64
 12  region               773 non-null    int64
 13  diameter_1           773 non-null    int64
 14  diameter_2           773 non-null    int64
 15  diagnostic           773 non-null    int64
 16  itch                 773 non-null    boolean
 17  grew                 773 non-null    boolean
 18  hurt                 773 non-null    boolean
 19  changed              773 non-null    boolean
 20  bleed                773 non-null    boolean
 21  elevation            773 non-null    boolean
 22  biopsed              773 non-null    bool
 23  malignant            773 non-null    bool
dtypes: bool(2), boolean(13), int64(9)
memory usage: 81.5 KB

In [66]:
df.describe(include="all")

,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,biopsed,malignant
count,773,773,773.000000,773.000000,773.000000,773,773.000000,773,773,773,...,773.000000,773.000000,773,773,773,773,773,773,773,773
unique,2,2,NaN,NaN,NaN,2,NaN,2,2,2,...,NaN,NaN,2,2,2,2,2,2,2,2
top,False,False,NaN,NaN,NaN,False,NaN,False,True,True,...,NaN,NaN,True,True,False,False,False,True,True,True
freq,674,587,NaN,NaN,NaN,454,NaN,420,419,454,...,NaN,NaN,551,442,576,673,488,533,657,491
mean,NaN,NaN,4.561449,4.385511,1.376455,NaN,0.487710,NaN,NaN,NaN,...,0.042691,1.219922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,2.554162,2.776921,0.592976,NaN,0.500173,NaN,NaN,NaN,...,0.220666,1.343095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,0.000000,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,2.000000,2.000000,1.000000,NaN,0.000000,NaN,NaN,NaN,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,4.000000,3.000000,1.000000,NaN,0.000000,NaN,NaN,NaN,...,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,7.000000,7.000000,2.000000,NaN,1.000000,NaN,NaN,NaN,...,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,9.000000,10.000000,2.000000,NaN,1.000000,NaN,NaN,NaN,...,2.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN