In [3]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [4]:
df = pd.read_csv("../data/skin-lesion-data/metadata.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2298 entries, 0 to 2297
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           2298 non-null   object
 1   lesion_id            2298 non-null   int64
 2   smoke                1494 non-null   object
 3   drink                1494 non-null   object
 4   background_father    1480 non-null   object
 5   background_mother    1476 non-null   object
 6   age                  2298 non-null   int64
 7   pesticide            1494 non-null   object
 8   gender               1494 non-null   object
 9   skin_cancer_history  1494 non-null   object
 10  cancer_history       1494 non-null   object
 11  has_piped_water      1494 non-null   object
 12  has_sewage_system    1494 non-null   object
 13  fitspatrick          1494 non-null   float64
 14  region               2298 non-null   object
 15  diameter_1           1494 non-null   float64
 16  diameter_2           1494 non-null   float64
 17  diagnostic           2298 non-null   object
 18  itch                 2298 non-null   object
 19  grew                 2298 non-null   object
 20  hurt                 2298 non-null   object
 21  changed              2298 non-null   object
 22  bleed                2298 non-null   object
 23  elevation            2298 non-null   object
 24  img_id               2298 non-null   object
 25  biopsed              2298 non-null   bool
dtypes: bool(1), float64(3), int64(2), object(20)
memory usage: 451.2+ KB

In [6]:
df.describe(include="all")

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
count,2298,2298.000000,1494,1494,1480,1476,2298.000000,1494,1494,1494,...,1494.000000,2298,2298,2298,2298,2298,2298,2298,2298,2298
unique,1373,NaN,2,2,13,11,NaN,2,2,2,...,NaN,6,3,3,3,3,3,3,2298,2
top,PAT_645,NaN,False,False,POMERANIA,POMERANIA,NaN,False,FEMALE,False,...,NaN,BCC,True,False,False,False,False,True,PAT_1516_1765_530.png,True
freq,10,NaN,1292,1126,530,533,NaN,897,753,813,...,NaN,845,1455,971,1891,1700,1678,1433,1,1342
mean,NaN,1529.933856,NaN,NaN,NaN,NaN,60.464752,NaN,NaN,NaN,...,8.852209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,1196.285644,NaN,NaN,NaN,NaN,15.894866,NaN,NaN,NaN,...,5.797036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,6.000000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,720.500000,NaN,NaN,NaN,NaN,52.000000,NaN,NaN,NaN,...,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1297.000000,NaN,NaN,NaN,NaN,62.000000,NaN,NaN,NaN,...,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1782.750000,NaN,NaN,NaN,NaN,72.000000,NaN,NaN,NaN,...,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,4820.000000,NaN,NaN,NaN,NaN,94.000000,NaN,NaN,NaN,...,70.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.head()

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
0,PAT_1516,1765,NaN,NaN,NaN,NaN,8,NaN,NaN,NaN,...,NaN,NEV,False,False,False,False,False,False,PAT_1516_1765_530.png,False
1,PAT_46,881,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,...,5.0,BCC,True,True,False,True,True,True,PAT_46_881_939.png,True
2,PAT_1545,1867,NaN,NaN,NaN,NaN,77,NaN,NaN,NaN,...,NaN,ACK,True,False,False,False,False,False,PAT_1545_1867_547.png,False
3,PAT_1989,4061,NaN,NaN,NaN,NaN,75,NaN,NaN,NaN,...,NaN,ACK,True,False,False,False,False,False,PAT_1989_4061_934.png,False
4,PAT_684,1302,False,True,POMERANIA,POMERANIA,79,False,MALE,True,...,5.0,BCC,True,True,False,False,True,True,PAT_684_1302_588.png,True

# Changing Data Types

There appears to be a lot of columns with their dataype set as `object`. This is most likely due to the fact that there are `NaN` values everywhere.

In [8]:
df.loc[0]

patient_id                          PAT_1516
lesion_id                               1765
smoke                                    NaN
drink                                    NaN
background_father                        NaN
background_mother                        NaN
age                                        8
pesticide                                NaN
gender                                   NaN
skin_cancer_history                      NaN
cancer_history                           NaN
has_piped_water                          NaN
has_sewage_system                        NaN
fitspatrick                              NaN
region                                   ARM
diameter_1                               NaN
diameter_2                               NaN
diagnostic                               NEV
itch                                   False
grew                                   False
hurt                                   False
changed                                False
bleed                                  False
elevation                              False
img_id                 PAT_1516_1765_530.png
biopsed                                False
Name: 0, dtype: object

In [9]:
df["patient_id"]

0       PAT_1516
1         PAT_46
2       PAT_1545
3       PAT_1989
4        PAT_684
          ...
2293    PAT_1708
2294      PAT_46
2295    PAT_1343
2296     PAT_326
2297    PAT_1714
Name: patient_id, Length: 2298, dtype: object

In [10]:
df["patient_id"] = df["patient_id"].astype("string")
df["patient_id"]

0       PAT_1516
1         PAT_46
2       PAT_1545
3       PAT_1989
4        PAT_684
          ...
2293    PAT_1708
2294      PAT_46
2295    PAT_1343
2296     PAT_326
2297    PAT_1714
Name: patient_id, Length: 2298, dtype: string

In [11]:
df["smoke"]

0         NaN
1       False
2         NaN
3         NaN
4       False
        ...
2293      NaN
2294    False
2295      NaN
2296    False
2297      NaN
Name: smoke, Length: 2298, dtype: object

In [12]:
df.loc[0]["smoke"]

nan

In [13]:
type(df.loc[0]["smoke"])

float

In [14]:
df["smoke"] = df["smoke"].astype("boolean")
df["smoke"]

0        <NA>
1       False
2        <NA>
3        <NA>
4       False
        ...
2293     <NA>
2294    False
2295     <NA>
2296    False
2297     <NA>
Name: smoke, Length: 2298, dtype: boolean

In [15]:
df.loc[df["smoke"].isnull()]

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
0,PAT_1516,1765,<NA>,NaN,NaN,NaN,8,NaN,NaN,NaN,...,NaN,NEV,False,False,False,False,False,False,PAT_1516_1765_530.png,False
2,PAT_1545,1867,<NA>,NaN,NaN,NaN,77,NaN,NaN,NaN,...,NaN,ACK,True,False,False,False,False,False,PAT_1545_1867_547.png,False
3,PAT_1989,4061,<NA>,NaN,NaN,NaN,75,NaN,NaN,NaN,...,NaN,ACK,True,False,False,False,False,False,PAT_1989_4061_934.png,False
5,PAT_1549,1882,<NA>,NaN,NaN,NaN,53,NaN,NaN,NaN,...,NaN,SEK,True,False,False,False,False,True,PAT_1549_1882_230.png,False
8,PAT_1995,4080,<NA>,NaN,NaN,NaN,68,NaN,NaN,NaN,...,NaN,ACK,True,False,False,True,False,False,PAT_1995_4080_695.png,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2288,PAT_1407,1402,<NA>,NaN,NaN,NaN,81,NaN,NaN,NaN,...,NaN,ACK,True,False,False,False,False,False,PAT_1407_1402_562.png,False
2290,PAT_1294,1031,<NA>,NaN,NaN,NaN,35,NaN,NaN,NaN,...,NaN,ACK,True,False,True,False,False,False,PAT_1294_1031_466.png,False
2293,PAT_1708,3156,<NA>,NaN,NaN,NaN,73,NaN,NaN,NaN,...,NaN,ACK,True,False,False,False,False,False,PAT_1708_3156_175.png,False
2295,PAT_1343,1217,<NA>,NaN,NaN,NaN,74,NaN,NaN,NaN,...,NaN,SEK,False,False,False,False,False,False,PAT_1343_1217_404.png,False
2297,PAT_1714,3189,<NA>,NaN,NaN,NaN,41,NaN,NaN,NaN,...,NaN,SEK,False,True,False,False,False,True,PAT_1714_3189_989.png,False

In [16]:
df["drink"] = df["drink"].astype("boolean")
df["drink"]

0        <NA>
1       False
2        <NA>
3        <NA>
4        True
        ...
2293     <NA>
2294    False
2295     <NA>
2296    False
2297     <NA>
Name: drink, Length: 2298, dtype: boolean

In [17]:
df["background_father"]

0             NaN
1       POMERANIA
2             NaN
3             NaN
4       POMERANIA
          ...
2293          NaN
2294    POMERANIA
2295          NaN
2296    POMERANIA
2297          NaN
Name: background_father, Length: 2298, dtype: object

In [18]:
df["background_father"] = df["background_father"].astype("category")
df["background_father"]

0             NaN
1       POMERANIA
2             NaN
3             NaN
4       POMERANIA
          ...
2293          NaN
2294    POMERANIA
2295          NaN
2296    POMERANIA
2297          NaN
Name: background_father, Length: 2298, dtype: category
Categories (13, object): ['AUSTRIA', 'BRASIL', 'BRAZIL', 'CZECH', ..., 'POMERANIA', 'PORTUGAL', 'SPAIN', 'UNK']

In [19]:
df["background_father"].cat.categories

Index(['AUSTRIA', 'BRASIL', 'BRAZIL', 'CZECH', 'GERMANY', 'ISRAEL', 'ITALY',
       'NETHERLANDS', 'POLAND', 'POMERANIA', 'PORTUGAL', 'SPAIN', 'UNK'],
      dtype='object')

In [20]:
df["background_father"] = df["background_father"].replace("UNK", "OTHER")

/var/folders/sp/kjzzm68x2djdfrnp736n59bm0000gn/T/ipykernel_71980/2235619274.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df["background_father"] = df["background_father"].replace("UNK", "OTHER")

In [21]:
df["background_father"].cat.categories

Index(['AUSTRIA', 'BRASIL', 'BRAZIL', 'CZECH', 'GERMANY', 'ISRAEL', 'ITALY',
       'NETHERLANDS', 'POLAND', 'POMERANIA', 'PORTUGAL', 'SPAIN', 'OTHER'],
      dtype='object')

In [22]:
df["background_mother"] = df["background_mother"].astype("category")
df["background_mother"]

0             NaN
1       POMERANIA
2             NaN
3             NaN
4       POMERANIA
          ...
2293          NaN
2294    POMERANIA
2295          NaN
2296    POMERANIA
2297          NaN
Name: background_mother, Length: 2298, dtype: category
Categories (11, object): ['BRAZIL', 'FRANCE', 'GERMANY', 'ITALY', ..., 'POMERANIA', 'PORTUGAL', 'SPAIN', 'UNK']

In [23]:
df["background_mother"].cat.categories

Index(['BRAZIL', 'FRANCE', 'GERMANY', 'ITALY', 'NETHERLANDS', 'NORWAY',
       'POLAND', 'POMERANIA', 'PORTUGAL', 'SPAIN', 'UNK'],
      dtype='object')

In [24]:
df["background_mother"] = df["background_mother"].replace("UNK", "OTHER")

/var/folders/sp/kjzzm68x2djdfrnp736n59bm0000gn/T/ipykernel_71980/2367761035.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df["background_mother"] = df["background_mother"].replace("UNK", "OTHER")

In [25]:
df["background_mother"].cat.categories

Index(['BRAZIL', 'FRANCE', 'GERMANY', 'ITALY', 'NETHERLANDS', 'NORWAY',
       'POLAND', 'POMERANIA', 'PORTUGAL', 'SPAIN', 'OTHER'],
      dtype='object')

In [26]:
df["pesticide"]

0         NaN
1       False
2         NaN
3         NaN
4       False
        ...
2293      NaN
2294    False
2295      NaN
2296     True
2297      NaN
Name: pesticide, Length: 2298, dtype: object

In [27]:
df["pesticide"] = df["pesticide"].astype("boolean")
df["pesticide"]

0        <NA>
1       False
2        <NA>
3        <NA>
4       False
        ...
2293     <NA>
2294    False
2295     <NA>
2296     True
2297     <NA>
Name: pesticide, Length: 2298, dtype: boolean

In [28]:
df["gender"]

0          NaN
1       FEMALE
2          NaN
3          NaN
4         MALE
         ...
2293       NaN
2294    FEMALE
2295       NaN
2296    FEMALE
2297       NaN
Name: gender, Length: 2298, dtype: object

In [29]:
df["gender"] = df["gender"].astype("category")
df["gender"]

0          NaN
1       FEMALE
2          NaN
3          NaN
4         MALE
         ...
2293       NaN
2294    FEMALE
2295       NaN
2296    FEMALE
2297       NaN
Name: gender, Length: 2298, dtype: category
Categories (2, object): ['FEMALE', 'MALE']

In [30]:
df["gender"].cat.categories

Index(['FEMALE', 'MALE'], dtype='object')

In [31]:
df["skin_cancer_history"]

0        NaN
1       True
2        NaN
3        NaN
4       True
        ...
2293     NaN
2294    True
2295     NaN
2296    True
2297     NaN
Name: skin_cancer_history, Length: 2298, dtype: object

In [32]:
df["skin_cancer_history"] = df["skin_cancer_history"].astype("boolean")
df["skin_cancer_history"]

0       <NA>
1       True
2       <NA>
3       <NA>
4       True
        ...
2293    <NA>
2294    True
2295    <NA>
2296    True
2297    <NA>
Name: skin_cancer_history, Length: 2298, dtype: boolean

In [33]:
df["cancer_history"] = df["cancer_history"].astype("boolean")
df["cancer_history"]

0        <NA>
1        True
2        <NA>
3        <NA>
4       False
        ...
2293     <NA>
2294     True
2295     <NA>
2296     True
2297     <NA>
Name: cancer_history, Length: 2298, dtype: boolean

In [34]:
df["has_piped_water"]

0         NaN
1        True
2         NaN
3         NaN
4       False
        ...
2293      NaN
2294     True
2295      NaN
2296    False
2297      NaN
Name: has_piped_water, Length: 2298, dtype: object

In [35]:
df["has_piped_water"] = df["has_piped_water"].astype("boolean")
df["has_piped_water"]

0        <NA>
1        True
2        <NA>
3        <NA>
4       False
        ...
2293     <NA>
2294     True
2295     <NA>
2296    False
2297     <NA>
Name: has_piped_water, Length: 2298, dtype: boolean

In [36]:
df["has_sewage_system"] = df["has_sewage_system"].astype("boolean")
df["has_sewage_system"]

0        <NA>
1        True
2        <NA>
3        <NA>
4       False
        ...
2293     <NA>
2294     True
2295     <NA>
2296    False
2297     <NA>
Name: has_sewage_system, Length: 2298, dtype: boolean

In [37]:
df["fitspatrick"]

0       NaN
1       3.0
2       NaN
3       NaN
4       1.0
       ...
2293    NaN
2294    3.0
2295    NaN
2296    3.0
2297    NaN
Name: fitspatrick, Length: 2298, dtype: float64

In [38]:
df["region"]

0           ARM
1          NECK
2          FACE
3          HAND
4       FOREARM
         ...
2293       HAND
2294      CHEST
2295    FOREARM
2296       FACE
2297      THIGH
Name: region, Length: 2298, dtype: object

In [39]:
df["region"] = df["region"].astype("category")
df["region"]

0           ARM
1          NECK
2          FACE
3          HAND
4       FOREARM
         ...
2293       HAND
2294      CHEST
2295    FOREARM
2296       FACE
2297      THIGH
Name: region, Length: 2298, dtype: category
Categories (14, object): ['ABDOMEN', 'ARM', 'BACK', 'CHEST', ..., 'NECK', 'NOSE', 'SCALP', 'THIGH']

In [40]:
df["region"].cat.categories

Index(['ABDOMEN', 'ARM', 'BACK', 'CHEST', 'EAR', 'FACE', 'FOOT', 'FOREARM',
       'HAND', 'LIP', 'NECK', 'NOSE', 'SCALP', 'THIGH'],
      dtype='object')

In [41]:
df["diameter_1"]

0        NaN
1        6.0
2        NaN
3        NaN
4        5.0
        ...
2293     NaN
2294    13.0
2295     NaN
2296     5.0
2297     NaN
Name: diameter_1, Length: 2298, dtype: float64

In [42]:
df["diagnostic"]

0       NEV
1       BCC
2       ACK
3       ACK
4       BCC
       ...
2293    ACK
2294    BCC
2295    SEK
2296    BCC
2297    SEK
Name: diagnostic, Length: 2298, dtype: object

In [43]:
df["diagnostic"] = df["diagnostic"].astype("category")
df["diagnostic"]

0       NEV
1       BCC
2       ACK
3       ACK
4       BCC
       ...
2293    ACK
2294    BCC
2295    SEK
2296    BCC
2297    SEK
Name: diagnostic, Length: 2298, dtype: category
Categories (6, object): ['ACK', 'BCC', 'MEL', 'NEV', 'SCC', 'SEK']

In [44]:
df["diagnostic"].cat.categories

Index(['ACK', 'BCC', 'MEL', 'NEV', 'SCC', 'SEK'], dtype='object')

In [45]:
df["itch"]

0       False
1        True
2        True
3        True
4        True
        ...
2293     True
2294     True
2295    False
2296     True
2297    False
Name: itch, Length: 2298, dtype: object

In [46]:
df["itch"].unique()

array(['False', 'True', 'UNK'], dtype=object)

In [47]:
df["itch"] = df["itch"].replace("True", True)
df["itch"] = df["itch"].replace("False", False)
df["itch"] = df["itch"].replace("UNK", pd.NA)

In [48]:
df["itch"].unique()

array([False, True, <NA>], dtype=object)

In [49]:
df["itch"] = df["itch"].astype("boolean")
df["itch"]

0       False
1        True
2        True
3        True
4        True
        ...
2293     True
2294     True
2295    False
2296     True
2297    False
Name: itch, Length: 2298, dtype: boolean

In [50]:
df["grew"]

0       False
1        True
2       False
3       False
4        True
        ...
2293    False
2294     True
2295    False
2296    False
2297     True
Name: grew, Length: 2298, dtype: object

In [51]:
df["grew"].unique()

array(['False', 'True', 'UNK'], dtype=object)

In [52]:
df["grew"] = df["grew"].replace("True", True)
df["grew"] = df["grew"].replace("False", False)
df["grew"] = df["grew"].replace("UNK", pd.NA)

In [53]:
df["grew"] = df["grew"].astype("boolean")
df["grew"]

0       False
1        True
2       False
3       False
4        True
        ...
2293    False
2294     True
2295    False
2296    False
2297     True
Name: grew, Length: 2298, dtype: boolean

In [54]:
df["hurt"]

0       False
1       False
2       False
3       False
4       False
        ...
2293    False
2294    False
2295    False
2296    False
2297    False
Name: hurt, Length: 2298, dtype: object

In [55]:
df["hurt"].unique()

array(['False', 'True', 'UNK'], dtype=object)

In [56]:
df["hurt"] = df["hurt"].replace("True", True)
df["hurt"] = df["hurt"].replace("False", False)
df["hurt"] = df["hurt"].replace("UNK", pd.NA)

In [57]:
df["hurt"] = df["hurt"].astype("boolean")
df["hurt"]

0       False
1       False
2       False
3       False
4       False
        ...
2293    False
2294    False
2295    False
2296    False
2297    False
Name: hurt, Length: 2298, dtype: boolean

In [58]:
df["changed"]

0       False
1        True
2       False
3       False
4       False
        ...
2293    False
2294     True
2295    False
2296    False
2297    False
Name: changed, Length: 2298, dtype: object

In [59]:
df["changed"].unique()

array(['False', 'True', 'UNK'], dtype=object)

In [60]:
df["changed"] = df["changed"].replace("True", True)
df["changed"] = df["changed"].replace("False", False)
df["changed"] = df["changed"].replace("UNK", pd.NA)

In [61]:
df["changed"] = df["changed"].astype("boolean")
df["changed"]

0       False
1        True
2       False
3       False
4       False
        ...
2293    False
2294     True
2295    False
2296    False
2297    False
Name: changed, Length: 2298, dtype: boolean

In [62]:
df["bleed"]

0       False
1        True
2       False
3       False
4        True
        ...
2293    False
2294    False
2295    False
2296    False
2297    False
Name: bleed, Length: 2298, dtype: object

In [63]:
df["bleed"].unique()

array(['False', 'True', 'UNK'], dtype=object)

In [64]:
df["bleed"] = df["bleed"].replace("True", True)
df["bleed"] = df["bleed"].replace("False", False)
df["bleed"] = df["bleed"].replace("UNK", pd.NA)

In [65]:
df["bleed"] = df["bleed"].astype("boolean")
df["bleed"]

0       False
1        True
2       False
3       False
4        True
        ...
2293    False
2294    False
2295    False
2296    False
2297    False
Name: bleed, Length: 2298, dtype: boolean

In [66]:
df["elevation"]

0       False
1        True
2       False
3       False
4        True
        ...
2293    False
2294    False
2295    False
2296     True
2297     True
Name: elevation, Length: 2298, dtype: object

In [67]:
df["elevation"].unique()

array(['False', 'True', 'UNK'], dtype=object)

In [68]:
df["elevation"] = df["elevation"].replace("True", True)
df["elevation"] = df["elevation"].replace("False", False)
df["elevation"] = df["elevation"].replace("UNK", pd.NA)

In [69]:
df["elevation"] = df["elevation"].astype("boolean")
df["elevation"]

0       False
1        True
2       False
3       False
4        True
        ...
2293    False
2294    False
2295    False
2296     True
2297     True
Name: elevation, Length: 2298, dtype: boolean

In [70]:
df["img_id"]

0       PAT_1516_1765_530.png
1          PAT_46_881_939.png
2       PAT_1545_1867_547.png
3       PAT_1989_4061_934.png
4        PAT_684_1302_588.png
                ...
2293    PAT_1708_3156_175.png
2294       PAT_46_880_140.png
2295    PAT_1343_1217_404.png
2296      PAT_326_690_823.png
2297    PAT_1714_3189_989.png
Name: img_id, Length: 2298, dtype: object

In [71]:
df["img_id"] = df["img_id"].astype("string")
df["img_id"]

0       PAT_1516_1765_530.png
1          PAT_46_881_939.png
2       PAT_1545_1867_547.png
3       PAT_1989_4061_934.png
4        PAT_684_1302_588.png
                ...
2293    PAT_1708_3156_175.png
2294       PAT_46_880_140.png
2295    PAT_1343_1217_404.png
2296      PAT_326_690_823.png
2297    PAT_1714_3189_989.png
Name: img_id, Length: 2298, dtype: string

In [72]:
# https://stackoverflow.com/questions/26640129/search-for-string-in-all-pandas-dataframe-columns-and-filter
mask = np.column_stack([df[col].astype(str).str.contains(r"UNK", na=False) for col in df])
df.loc[mask.any(axis=1)]

Empty DataFrame
Columns: [patient_id, lesion_id, smoke, drink, background_father, background_mother, age, pesticide, gender, skin_cancer_history, cancer_history, has_piped_water, has_sewage_system, fitspatrick, region, diameter_1, diameter_2, diagnostic, itch, grew, hurt, changed, bleed, elevation, img_id, biopsed]
Index: []

[0 rows x 26 columns]

# Drop missing values

Now that the types are correct we can focus on dropping rows with important or many missing values.

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2298 entries, 0 to 2297
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           2298 non-null   string
 1   lesion_id            2298 non-null   int64
 2   smoke                1494 non-null   boolean
 3   drink                1494 non-null   boolean
 4   background_father    1480 non-null   category
 5   background_mother    1476 non-null   category
 6   age                  2298 non-null   int64
 7   pesticide            1494 non-null   boolean
 8   gender               1494 non-null   category
 9   skin_cancer_history  1494 non-null   boolean
 10  cancer_history       1494 non-null   boolean
 11  has_piped_water      1494 non-null   boolean
 12  has_sewage_system    1494 non-null   boolean
 13  fitspatrick          1494 non-null   float64
 14  region               2298 non-null   category
 15  diameter_1           1494 non-null   float64
 16  diameter_2           1494 non-null   float64
 17  diagnostic           2298 non-null   category
 18  itch                 2292 non-null   boolean
 19  grew                 1896 non-null   boolean
 20  hurt                 2288 non-null   boolean
 21  changed              1902 non-null   boolean
 22  bleed                2292 non-null   boolean
 23  elevation            2296 non-null   boolean
 24  img_id               2298 non-null   string
 25  biopsed              2298 non-null   bool
dtypes: bool(1), boolean(13), category(5), float64(3), int64(2), string(2)
memory usage: 199.6 KB

In [74]:
df.describe(include="all")

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
count,2298,2298.000000,1494,1494,1480,1476,2298.000000,1494,1494,1494,...,1494.000000,2298,2292,1896,2288,1902,2292,2296,2298,2298
unique,1373,NaN,2,2,13,11,NaN,2,2,2,...,NaN,6,2,2,2,2,2,2,2298,2
top,PAT_645,NaN,False,False,POMERANIA,POMERANIA,NaN,False,FEMALE,False,...,NaN,BCC,True,False,False,False,False,True,PAT_1516_1765_530.png,True
freq,10,NaN,1292,1126,530,533,NaN,897,753,813,...,NaN,845,1455,971,1891,1700,1678,1433,1,1342
mean,NaN,1529.933856,NaN,NaN,NaN,NaN,60.464752,NaN,NaN,NaN,...,8.852209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,1196.285644,NaN,NaN,NaN,NaN,15.894866,NaN,NaN,NaN,...,5.797036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,6.000000,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,720.500000,NaN,NaN,NaN,NaN,52.000000,NaN,NaN,NaN,...,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,1297.000000,NaN,NaN,NaN,NaN,62.000000,NaN,NaN,NaN,...,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1782.750000,NaN,NaN,NaN,NaN,72.000000,NaN,NaN,NaN,...,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,4820.000000,NaN,NaN,NaN,NaN,94.000000,NaN,NaN,NaN,...,70.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
df.head()

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
0,PAT_1516,1765,<NA>,<NA>,NaN,NaN,8,<NA>,NaN,<NA>,...,NaN,NEV,False,False,False,False,False,False,PAT_1516_1765_530.png,False
1,PAT_46,881,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,...,5.0,BCC,True,True,False,True,True,True,PAT_46_881_939.png,True
2,PAT_1545,1867,<NA>,<NA>,NaN,NaN,77,<NA>,NaN,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1545_1867_547.png,False
3,PAT_1989,4061,<NA>,<NA>,NaN,NaN,75,<NA>,NaN,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1989_4061_934.png,False
4,PAT_684,1302,False,True,POMERANIA,POMERANIA,79,False,MALE,True,...,5.0,BCC,True,True,False,False,True,True,PAT_684_1302_588.png,True

In [76]:
df.isnull().sum()

patient_id               0
lesion_id                0
smoke                  804
drink                  804
background_father      818
background_mother      822
age                      0
pesticide              804
gender                 804
skin_cancer_history    804
cancer_history         804
has_piped_water        804
has_sewage_system      804
fitspatrick            804
region                   0
diameter_1             804
diameter_2             804
diagnostic               0
itch                     6
grew                   402
hurt                    10
changed                396
bleed                    6
elevation                2
img_id                   0
biopsed                  0
dtype: int64

In [108]:
df = df.dropna()

In [109]:
df

,patient_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
1,PAT_46,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,True,...,5.0,BCC,True,True,False,True,True,True,PAT_46_881_939.png,True
4,PAT_684,False,True,POMERANIA,POMERANIA,79,False,MALE,True,False,...,5.0,BCC,True,True,False,False,True,True,PAT_684_1302_588.png,True
6,PAT_778,False,True,GERMANY,ITALY,52,False,FEMALE,False,True,...,10.0,BCC,False,True,False,True,True,True,PAT_778_1471_835.png,True
7,PAT_117,False,False,POMERANIA,POMERANIA,74,True,FEMALE,False,False,...,10.0,BCC,True,True,True,False,True,True,PAT_117_179_983.png,True
9,PAT_705,False,True,GERMANY,GERMANY,58,True,FEMALE,True,True,...,7.0,ACK,False,True,False,False,False,False,PAT_705_4015_413.png,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,PAT_190,False,False,POMERANIA,POMERANIA,61,True,MALE,False,True,...,9.0,BCC,True,True,True,False,True,False,PAT_190_291_366.png,True
2284,PAT_498,False,True,POMERANIA,POMERANIA,60,True,FEMALE,True,False,...,2.0,ACK,False,False,False,False,False,False,PAT_498_944_488.png,True
2286,PAT_414,False,False,OTHER,ITALY,20,True,FEMALE,False,False,...,2.0,ACK,False,False,False,False,False,True,PAT_414_822_420.png,True
2287,PAT_754,False,False,ITALY,GERMANY,75,False,MALE,True,False,...,34.0,MEL,False,True,False,False,False,False,PAT_754_1429_380.png,True
2289,PAT_386,True,False,POMERANIA,POMERANIA,66,False,MALE,True,False,...,15.0,ACK,True,False,True,False,True,True,PAT_386_785_536.png,True

# Duplicate Entries

It looks like the some patients have multiple entries into the same dataset. They also appear to have the same lesions sometimes, we should look into this and remove duplicate data.

In [110]:
df.loc[df["patient_id"] == "PAT_1516"]

Empty DataFrame
Columns: [patient_id, smoke, drink, background_father, background_mother, age, pesticide, gender, skin_cancer_history, cancer_history, has_piped_water, has_sewage_system, fitspatrick, region, diameter_1, diameter_2, diagnostic, itch, grew, hurt, changed, bleed, elevation, img_id, biopsed]
Index: []

[0 rows x 25 columns]

In [111]:
df

,patient_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
1,PAT_46,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,True,...,5.0,BCC,True,True,False,True,True,True,PAT_46_881_939.png,True
4,PAT_684,False,True,POMERANIA,POMERANIA,79,False,MALE,True,False,...,5.0,BCC,True,True,False,False,True,True,PAT_684_1302_588.png,True
6,PAT_778,False,True,GERMANY,ITALY,52,False,FEMALE,False,True,...,10.0,BCC,False,True,False,True,True,True,PAT_778_1471_835.png,True
7,PAT_117,False,False,POMERANIA,POMERANIA,74,True,FEMALE,False,False,...,10.0,BCC,True,True,True,False,True,True,PAT_117_179_983.png,True
9,PAT_705,False,True,GERMANY,GERMANY,58,True,FEMALE,True,True,...,7.0,ACK,False,True,False,False,False,False,PAT_705_4015_413.png,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,PAT_190,False,False,POMERANIA,POMERANIA,61,True,MALE,False,True,...,9.0,BCC,True,True,True,False,True,False,PAT_190_291_366.png,True
2284,PAT_498,False,True,POMERANIA,POMERANIA,60,True,FEMALE,True,False,...,2.0,ACK,False,False,False,False,False,False,PAT_498_944_488.png,True
2286,PAT_414,False,False,OTHER,ITALY,20,True,FEMALE,False,False,...,2.0,ACK,False,False,False,False,False,True,PAT_414_822_420.png,True
2287,PAT_754,False,False,ITALY,GERMANY,75,False,MALE,True,False,...,34.0,MEL,False,True,False,False,False,False,PAT_754_1429_380.png,True
2289,PAT_386,True,False,POMERANIA,POMERANIA,66,False,MALE,True,False,...,15.0,ACK,True,False,True,False,True,True,PAT_386_785_536.png,True

In [112]:
df.describe(include="all")

,patient_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
count,773,773,773,773,773,773.000000,773,773,773,773,...,773.000000,773,773,773,773,773,773,773,773,773
unique,539,2,2,11,11,NaN,2,2,2,2,...,NaN,6,2,2,2,2,2,2,773,2
top,PAT_645,False,False,POMERANIA,POMERANIA,NaN,False,FEMALE,False,True,...,NaN,BCC,True,True,False,False,False,True,PAT_46_881_939.png,True
freq,8,674,587,280,282,NaN,454,396,420,419,...,NaN,392,551,442,576,673,488,533,1,657
mean,NaN,NaN,NaN,NaN,NaN,63.932730,NaN,NaN,NaN,NaN,...,8.381889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,14.101616,NaN,NaN,NaN,NaN,...,5.252375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,14.000000,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,...,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,64.000000,NaN,NaN,NaN,NaN,...,7.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,74.000000,NaN,NaN,NaN,NaN,...,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,94.000000,NaN,NaN,NaN,NaN,...,60.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
df["background_father"].unique()

[NaN, 'POMERANIA', 'GERMANY', 'BRAZIL', 'NETHERLANDS', ..., 'BRASIL', 'CZECH', 'AUSTRIA', 'SPAIN', 'ISRAEL']
Length: 14
Categories (13, object): ['AUSTRIA', 'BRASIL', 'BRAZIL', 'CZECH', ..., 'POMERANIA', 'PORTUGAL', 'SPAIN', 'OTHER']

In [83]:
df.loc[(df["background_father"] == "OTHER") | (df["background_mother"] == "OTHER")]

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
43,PAT_621,1183,False,False,OTHER,OTHER,34,False,MALE,False,...,12.0,NEV,False,<NA>,False,<NA>,False,False,PAT_621_1183_56.png,True
56,PAT_183,283,False,False,OTHER,OTHER,76,False,MALE,True,...,7.0,SCC,True,False,False,False,False,False,PAT_183_283_495.png,True
61,PAT_620,1176,False,True,OTHER,OTHER,35,False,MALE,True,...,7.0,BCC,False,<NA>,False,<NA>,False,True,PAT_620_1176_980.png,True
70,PAT_920,1747,False,False,OTHER,OTHER,56,True,FEMALE,False,...,5.0,BCC,True,<NA>,False,<NA>,False,True,PAT_920_1747_19.png,True
86,PAT_995,1867,False,False,OTHER,OTHER,49,False,FEMALE,False,...,20.0,MEL,False,True,False,True,False,True,PAT_995_1867_5.png,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2268,PAT_181,281,False,False,OTHER,OTHER,58,False,MALE,True,...,10.0,BCC,False,True,False,False,False,True,PAT_181_281_54.png,True
2280,PAT_681,1299,True,False,OTHER,SPAIN,71,True,MALE,True,...,5.0,BCC,False,<NA>,False,<NA>,False,True,PAT_681_1299_458.png,True
2281,PAT_747,1409,False,False,OTHER,BRAZIL,55,False,MALE,True,...,10.0,ACK,True,True,False,False,True,True,PAT_747_1409_466.png,True
2282,PAT_136,203,False,False,OTHER,OTHER,60,False,FEMALE,False,...,5.0,BCC,False,<NA>,False,<NA>,False,True,PAT_136_203_436.png,True
2286,PAT_414,822,False,False,OTHER,ITALY,20,True,FEMALE,False,...,2.0,ACK,False,False,False,False,False,True,PAT_414_822_420.png,True

In [84]:
same = ((df["skin_cancer_history"] == True) & (df["cancer_history"] == True)) | ((df["skin_cancer_history"] == False) & (df["cancer_history"] == False))
df.loc[same, ["skin_cancer_history", "cancer_history"]]

      skin_cancer_history  cancer_history
1                    True            True
7                   False           False
9                    True            True
13                   True            True
14                   True            True
...                   ...             ...
2286                False           False
2291                False           False
2292                 True            True
2294                 True            True
2296                 True            True

[764 rows x 2 columns]

In [85]:
df["region"].unique()

['ARM', 'NECK', 'FACE', 'HAND', 'FOREARM', ..., 'EAR', 'BACK', 'FOOT', 'ABDOMEN', 'LIP']
Length: 14
Categories (14, object): ['ABDOMEN', 'ARM', 'BACK', 'CHEST', ..., 'NECK', 'NOSE', 'SCALP', 'THIGH']

## Diameter

`diameter_1` seems to refer to the height

`diameter_2` seems to refer to the width

In [86]:
df[["diameter_1", "diameter_2", "img_id"]]

      diameter_1  diameter_2                 img_id
0            NaN         NaN  PAT_1516_1765_530.png
1            6.0         5.0     PAT_46_881_939.png
2            NaN         NaN  PAT_1545_1867_547.png
3            NaN         NaN  PAT_1989_4061_934.png
4            5.0         5.0   PAT_684_1302_588.png
...          ...         ...                    ...
2293         NaN         NaN  PAT_1708_3156_175.png
2294        13.0        12.0     PAT_46_880_140.png
2295         NaN         NaN  PAT_1343_1217_404.png
2296         5.0         4.0    PAT_326_690_823.png
2297         NaN         NaN  PAT_1714_3189_989.png

[2298 rows x 3 columns]

## Duplicates

There don't appear to be any duplicates initally, but when we remove the `img_id` we find that there are ~ 300 duplicates.

We should remove the duplicates to avoid overfitting.

In [87]:
df.loc[df.duplicated(subset=df.columns)]

Empty DataFrame
Columns: [patient_id, lesion_id, smoke, drink, background_father, background_mother, age, pesticide, gender, skin_cancer_history, cancer_history, has_piped_water, has_sewage_system, fitspatrick, region, diameter_1, diameter_2, diagnostic, itch, grew, hurt, changed, bleed, elevation, img_id, biopsed]
Index: []

[0 rows x 26 columns]

In [88]:
ignore = ["img_id"]
filters = [c for c in df.columns if c not in ignore]
df.loc[df.duplicated(keep=False, subset=filters)]

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
1,PAT_46,881,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,...,5.0,BCC,True,True,False,True,True,True,PAT_46_881_939.png,True
4,PAT_684,1302,False,True,POMERANIA,POMERANIA,79,False,MALE,True,...,5.0,BCC,True,True,False,False,True,True,PAT_684_1302_588.png,True
6,PAT_778,1471,False,True,GERMANY,ITALY,52,False,FEMALE,False,...,10.0,BCC,False,True,False,True,True,True,PAT_778_1471_835.png,True
10,PAT_2140,4726,<NA>,<NA>,NaN,NaN,45,<NA>,NaN,<NA>,...,NaN,ACK,True,False,False,False,False,True,PAT_2140_4726_141.png,False
13,PAT_636,1204,False,False,BRAZIL,BRAZIL,78,False,FEMALE,True,...,18.0,BCC,True,True,True,True,True,True,PAT_636_1204_521.png,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2281,PAT_747,1409,False,False,OTHER,BRAZIL,55,False,MALE,True,...,10.0,ACK,True,True,False,False,True,True,PAT_747_1409_466.png,True
2285,PAT_492,937,False,True,POMERANIA,POMERANIA,70,False,MALE,False,...,13.0,SCC,False,True,False,False,False,True,PAT_492_937_43.png,True
2288,PAT_1407,1402,<NA>,<NA>,NaN,NaN,81,<NA>,NaN,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1407_1402_562.png,False
2294,PAT_46,880,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,...,12.0,BCC,True,True,False,True,False,False,PAT_46_880_140.png,True
2296,PAT_326,690,False,False,POMERANIA,POMERANIA,58,True,FEMALE,True,...,4.0,BCC,True,False,False,False,False,True,PAT_326_690_823.png,True

In [89]:
df.loc[df.duplicated(keep="first", subset=filters)]

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
107,PAT_241,367,False,False,GERMANY,GERMANY,83,True,MALE,False,...,13.0,BCC,True,True,True,False,True,True,PAT_241_367_374.png,True
164,PAT_966,1825,False,False,POMERANIA,POMERANIA,46,False,FEMALE,False,...,5.0,MEL,True,True,False,True,False,False,PAT_966_1825_546.png,True
209,PAT_1582,2574,<NA>,<NA>,NaN,NaN,76,<NA>,NaN,<NA>,...,NaN,SEK,False,False,False,False,False,True,PAT_1582_2574_890.png,False
226,PAT_1094,381,<NA>,<NA>,NaN,NaN,41,<NA>,NaN,<NA>,...,NaN,ACK,False,False,False,False,False,False,PAT_1094_381_446.png,False
239,PAT_962,1823,False,False,POMERANIA,POMERANIA,52,True,MALE,True,...,3.0,BCC,True,True,True,False,False,True,PAT_962_1823_857.png,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2281,PAT_747,1409,False,False,OTHER,BRAZIL,55,False,MALE,True,...,10.0,ACK,True,True,False,False,True,True,PAT_747_1409_466.png,True
2285,PAT_492,937,False,True,POMERANIA,POMERANIA,70,False,MALE,False,...,13.0,SCC,False,True,False,False,False,True,PAT_492_937_43.png,True
2288,PAT_1407,1402,<NA>,<NA>,NaN,NaN,81,<NA>,NaN,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1407_1402_562.png,False
2294,PAT_46,880,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,...,12.0,BCC,True,True,False,True,False,False,PAT_46_880_140.png,True
2296,PAT_326,690,False,False,POMERANIA,POMERANIA,58,True,FEMALE,True,...,4.0,BCC,True,False,False,False,False,True,PAT_326_690_823.png,True

In [90]:
df.loc[df["lesion_id"] == 367]

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
82,PAT_241,367,False,False,GERMANY,GERMANY,83,True,MALE,False,...,13.0,BCC,True,True,True,False,True,True,PAT_241_367_89.png,True
107,PAT_241,367,False,False,GERMANY,GERMANY,83,True,MALE,False,...,13.0,BCC,True,True,True,False,True,True,PAT_241_367_374.png,True

In [91]:
df.loc[~df.duplicated(keep="first", subset=filters)]

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
0,PAT_1516,1765,<NA>,<NA>,NaN,NaN,8,<NA>,NaN,<NA>,...,NaN,NEV,False,False,False,False,False,False,PAT_1516_1765_530.png,False
1,PAT_46,881,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,...,5.0,BCC,True,True,False,True,True,True,PAT_46_881_939.png,True
2,PAT_1545,1867,<NA>,<NA>,NaN,NaN,77,<NA>,NaN,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1545_1867_547.png,False
3,PAT_1989,4061,<NA>,<NA>,NaN,NaN,75,<NA>,NaN,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1989_4061_934.png,False
4,PAT_684,1302,False,True,POMERANIA,POMERANIA,79,False,MALE,True,...,5.0,BCC,True,True,False,False,True,True,PAT_684_1302_588.png,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2291,PAT_273,421,False,False,POMERANIA,POMERANIA,41,True,MALE,False,...,5.0,BCC,True,<NA>,True,<NA>,True,True,PAT_273_421_905.png,True
2292,PAT_491,934,False,False,POMERANIA,POMERANIA,43,True,FEMALE,True,...,5.0,SCC,True,<NA>,False,<NA>,True,True,PAT_491_934_46.png,True
2293,PAT_1708,3156,<NA>,<NA>,NaN,NaN,73,<NA>,NaN,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1708_3156_175.png,False
2295,PAT_1343,1217,<NA>,<NA>,NaN,NaN,74,<NA>,NaN,<NA>,...,NaN,SEK,False,False,False,False,False,False,PAT_1343_1217_404.png,False
2297,PAT_1714,3189,<NA>,<NA>,NaN,NaN,41,<NA>,NaN,<NA>,...,NaN,SEK,False,True,False,False,False,True,PAT_1714_3189_989.png,False

### Remove duplicates

In [92]:
df = df.loc[~df.duplicated(keep="first", subset=filters)]
df

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
0,PAT_1516,1765,<NA>,<NA>,NaN,NaN,8,<NA>,NaN,<NA>,...,NaN,NEV,False,False,False,False,False,False,PAT_1516_1765_530.png,False
1,PAT_46,881,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,...,5.0,BCC,True,True,False,True,True,True,PAT_46_881_939.png,True
2,PAT_1545,1867,<NA>,<NA>,NaN,NaN,77,<NA>,NaN,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1545_1867_547.png,False
3,PAT_1989,4061,<NA>,<NA>,NaN,NaN,75,<NA>,NaN,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1989_4061_934.png,False
4,PAT_684,1302,False,True,POMERANIA,POMERANIA,79,False,MALE,True,...,5.0,BCC,True,True,False,False,True,True,PAT_684_1302_588.png,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2291,PAT_273,421,False,False,POMERANIA,POMERANIA,41,True,MALE,False,...,5.0,BCC,True,<NA>,True,<NA>,True,True,PAT_273_421_905.png,True
2292,PAT_491,934,False,False,POMERANIA,POMERANIA,43,True,FEMALE,True,...,5.0,SCC,True,<NA>,False,<NA>,True,True,PAT_491_934_46.png,True
2293,PAT_1708,3156,<NA>,<NA>,NaN,NaN,73,<NA>,NaN,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1708_3156_175.png,False
2295,PAT_1343,1217,<NA>,<NA>,NaN,NaN,74,<NA>,NaN,<NA>,...,NaN,SEK,False,False,False,False,False,False,PAT_1343_1217_404.png,False
2297,PAT_1714,3189,<NA>,<NA>,NaN,NaN,41,<NA>,NaN,<NA>,...,NaN,SEK,False,True,False,False,False,True,PAT_1714_3189_989.png,False

In [93]:
df.loc[df["lesion_id"] == 367]

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
82,PAT_241,367,False,False,GERMANY,GERMANY,83,True,MALE,False,...,13.0,BCC,True,True,True,False,True,True,PAT_241_367_89.png,True

## Lesion

If the same lesion appears twice it is refering to the same disease, should we remove?

In [94]:
df.loc[df.duplicated(keep=False, subset=['lesion_id'])]

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
2,PAT_1545,1867,<NA>,<NA>,NaN,NaN,77,<NA>,NaN,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1545_1867_547.png,False
7,PAT_117,179,False,False,POMERANIA,POMERANIA,74,True,FEMALE,False,...,10.0,BCC,True,True,True,False,True,True,PAT_117_179_983.png,True
28,PAT_302,651,True,False,GERMANY,GERMANY,64,True,MALE,True,...,10.0,BCC,True,True,True,False,True,True,PAT_302_651_529.png,True
30,PAT_107,160,False,False,POMERANIA,POMERANIA,82,False,FEMALE,False,...,8.0,SEK,False,True,False,False,False,True,PAT_107_160_609.png,True
32,PAT_1453,1567,<NA>,<NA>,NaN,NaN,52,<NA>,NaN,<NA>,...,NaN,NEV,False,False,False,False,False,True,PAT_1453_1567_250.png,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2273,PAT_1401,1373,<NA>,<NA>,NaN,NaN,51,<NA>,NaN,<NA>,...,NaN,NEV,False,True,False,False,False,True,PAT_1401_1373_881.png,False
2282,PAT_136,203,False,False,OTHER,OTHER,60,False,FEMALE,False,...,5.0,BCC,False,<NA>,False,<NA>,False,True,PAT_136_203_436.png,True
2287,PAT_754,1429,False,False,ITALY,GERMANY,75,False,MALE,True,...,34.0,MEL,False,True,False,False,False,False,PAT_754_1429_380.png,True
2290,PAT_1294,1031,<NA>,<NA>,NaN,NaN,35,<NA>,NaN,<NA>,...,NaN,ACK,True,False,True,False,False,False,PAT_1294_1031_466.png,False
2295,PAT_1343,1217,<NA>,<NA>,NaN,NaN,74,<NA>,NaN,<NA>,...,NaN,SEK,False,False,False,False,False,False,PAT_1343_1217_404.png,False

In [95]:
df.loc[df["lesion_id"] == 179]

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
7,PAT_117,179,False,False,POMERANIA,POMERANIA,74,True,FEMALE,False,...,10.0,BCC,True,True,True,False,True,True,PAT_117_179_983.png,True
1155,PAT_566,179,False,False,ITALY,BRAZIL,54,False,MALE,False,...,3.0,ACK,True,False,False,False,False,False,PAT_566_179_23.png,False

In [96]:
df.loc[df["lesion_id"] == 179, ["lesion_id", "region", "img_id"]]

      lesion_id region               img_id
7           179   FACE  PAT_117_179_983.png
1155        179    ARM   PAT_566_179_23.png

In [97]:
df.loc[df["lesion_id"] == 1517]

,patient_id,lesion_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
52,PAT_805,1517,False,False,GERMANY,GERMANY,58,False,FEMALE,False,...,8.0,SCC,True,True,False,False,False,True,PAT_805_1517_154.png,True
1289,PAT_281,1517,False,False,POMERANIA,POMERANIA,61,False,MALE,True,...,2.0,NEV,False,False,False,False,False,False,PAT_281_1517_293.png,False

In [98]:
df.loc[df["lesion_id"] == 1517, ["lesion_id", "region", "img_id"]]

      lesion_id region                img_id
52         1517   HAND  PAT_805_1517_154.png
1289       1517   BACK  PAT_281_1517_293.png

In [99]:
df.loc[df.duplicated(keep=False, subset=["patient_id", "lesion_id"])]

Empty DataFrame
Columns: [patient_id, lesion_id, smoke, drink, background_father, background_mother, age, pesticide, gender, skin_cancer_history, cancer_history, has_piped_water, has_sewage_system, fitspatrick, region, diameter_1, diameter_2, diagnostic, itch, grew, hurt, changed, bleed, elevation, img_id, biopsed]
Index: []

[0 rows x 26 columns]

### Drop `lesion_id`

`lesion_id` appears duplicated across different patients. This could either be a bug or intentional but regardless it no longer holds any useful information for us or the model.

In [100]:
df = df.drop("lesion_id", axis="columns")
df

,patient_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
0,PAT_1516,<NA>,<NA>,NaN,NaN,8,<NA>,NaN,<NA>,<NA>,...,NaN,NEV,False,False,False,False,False,False,PAT_1516_1765_530.png,False
1,PAT_46,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,True,...,5.0,BCC,True,True,False,True,True,True,PAT_46_881_939.png,True
2,PAT_1545,<NA>,<NA>,NaN,NaN,77,<NA>,NaN,<NA>,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1545_1867_547.png,False
3,PAT_1989,<NA>,<NA>,NaN,NaN,75,<NA>,NaN,<NA>,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1989_4061_934.png,False
4,PAT_684,False,True,POMERANIA,POMERANIA,79,False,MALE,True,False,...,5.0,BCC,True,True,False,False,True,True,PAT_684_1302_588.png,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2291,PAT_273,False,False,POMERANIA,POMERANIA,41,True,MALE,False,False,...,5.0,BCC,True,<NA>,True,<NA>,True,True,PAT_273_421_905.png,True
2292,PAT_491,False,False,POMERANIA,POMERANIA,43,True,FEMALE,True,True,...,5.0,SCC,True,<NA>,False,<NA>,True,True,PAT_491_934_46.png,True
2293,PAT_1708,<NA>,<NA>,NaN,NaN,73,<NA>,NaN,<NA>,<NA>,...,NaN,ACK,True,False,False,False,False,False,PAT_1708_3156_175.png,False
2295,PAT_1343,<NA>,<NA>,NaN,NaN,74,<NA>,NaN,<NA>,<NA>,...,NaN,SEK,False,False,False,False,False,False,PAT_1343_1217_404.png,False
2297,PAT_1714,<NA>,<NA>,NaN,NaN,41,<NA>,NaN,<NA>,<NA>,...,NaN,SEK,False,True,False,False,False,True,PAT_1714_3189_989.png,False

# Data Preprocessing

In [113]:
df

,patient_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
1,PAT_46,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,True,...,5.0,BCC,True,True,False,True,True,True,PAT_46_881_939.png,True
4,PAT_684,False,True,POMERANIA,POMERANIA,79,False,MALE,True,False,...,5.0,BCC,True,True,False,False,True,True,PAT_684_1302_588.png,True
6,PAT_778,False,True,GERMANY,ITALY,52,False,FEMALE,False,True,...,10.0,BCC,False,True,False,True,True,True,PAT_778_1471_835.png,True
7,PAT_117,False,False,POMERANIA,POMERANIA,74,True,FEMALE,False,False,...,10.0,BCC,True,True,True,False,True,True,PAT_117_179_983.png,True
9,PAT_705,False,True,GERMANY,GERMANY,58,True,FEMALE,True,True,...,7.0,ACK,False,True,False,False,False,False,PAT_705_4015_413.png,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,PAT_190,False,False,POMERANIA,POMERANIA,61,True,MALE,False,True,...,9.0,BCC,True,True,True,False,True,False,PAT_190_291_366.png,True
2284,PAT_498,False,True,POMERANIA,POMERANIA,60,True,FEMALE,True,False,...,2.0,ACK,False,False,False,False,False,False,PAT_498_944_488.png,True
2286,PAT_414,False,False,OTHER,ITALY,20,True,FEMALE,False,False,...,2.0,ACK,False,False,False,False,False,True,PAT_414_822_420.png,True
2287,PAT_754,False,False,ITALY,GERMANY,75,False,MALE,True,False,...,34.0,MEL,False,True,False,False,False,False,PAT_754_1429_380.png,True
2289,PAT_386,True,False,POMERANIA,POMERANIA,66,False,MALE,True,False,...,15.0,ACK,True,False,True,False,True,True,PAT_386_785_536.png,True

In [114]:
df.describe(include="all")

,patient_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,...,diameter_2,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed
count,773,773,773,773,773,773.000000,773,773,773,773,...,773.000000,773,773,773,773,773,773,773,773,773
unique,539,2,2,11,11,NaN,2,2,2,2,...,NaN,6,2,2,2,2,2,2,773,2
top,PAT_645,False,False,POMERANIA,POMERANIA,NaN,False,FEMALE,False,True,...,NaN,BCC,True,True,False,False,False,True,PAT_46_881_939.png,True
freq,8,674,587,280,282,NaN,454,396,420,419,...,NaN,392,551,442,576,673,488,533,1,657
mean,NaN,NaN,NaN,NaN,NaN,63.932730,NaN,NaN,NaN,NaN,...,8.381889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,14.101616,NaN,NaN,NaN,NaN,...,5.252375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,14.000000,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,...,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,64.000000,NaN,NaN,NaN,NaN,...,7.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,74.000000,NaN,NaN,NaN,NaN,...,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,94.000000,NaN,NaN,NaN,NaN,...,60.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [115]:
df["diagnostic"].unique()

['BCC', 'ACK', 'SCC', 'SEK', 'NEV', 'MEL']
Categories (6, object): ['ACK', 'BCC', 'MEL', 'NEV', 'SCC', 'SEK']

## Dataset is really unbalanced

In [116]:
df["diagnostic"].value_counts()

diagnostic
BCC    392
ACK    231
SCC     76
NEV     27
SEK     24
MEL     23
Name: count, dtype: int64

## Dataset is more balanced like this

In [117]:
malignant = ["BCC", "MEL", "SCC"]
diagnostic_amount = df["diagnostic"].value_counts()
cancerous_amount = {}
for d, v in diagnostic_amount.items():
    if d in malignant:
        cancerous_amount["malignant"] = cancerous_amount.get("malignant", 0) + v
    if not d in malignant:
        cancerous_amount["benign"] = cancerous_amount.get("benign", 0) + v
cancerous_amount

{'malignant': 491, 'benign': 282}

In [118]:
df["malignant"] = df["diagnostic"].isin(malignant)
df

/var/folders/sp/kjzzm68x2djdfrnp736n59bm0000gn/T/ipykernel_71980/1306355792.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["malignant"] = df["diagnostic"].isin(malignant)

,patient_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,...,diagnostic,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed,malignant
1,PAT_46,False,False,POMERANIA,POMERANIA,55,False,FEMALE,True,True,...,BCC,True,True,False,True,True,True,PAT_46_881_939.png,True,True
4,PAT_684,False,True,POMERANIA,POMERANIA,79,False,MALE,True,False,...,BCC,True,True,False,False,True,True,PAT_684_1302_588.png,True,True
6,PAT_778,False,True,GERMANY,ITALY,52,False,FEMALE,False,True,...,BCC,False,True,False,True,True,True,PAT_778_1471_835.png,True,True
7,PAT_117,False,False,POMERANIA,POMERANIA,74,True,FEMALE,False,False,...,BCC,True,True,True,False,True,True,PAT_117_179_983.png,True,True
9,PAT_705,False,True,GERMANY,GERMANY,58,True,FEMALE,True,True,...,ACK,False,True,False,False,False,False,PAT_705_4015_413.png,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,PAT_190,False,False,POMERANIA,POMERANIA,61,True,MALE,False,True,...,BCC,True,True,True,False,True,False,PAT_190_291_366.png,True,True
2284,PAT_498,False,True,POMERANIA,POMERANIA,60,True,FEMALE,True,False,...,ACK,False,False,False,False,False,False,PAT_498_944_488.png,True,False
2286,PAT_414,False,False,OTHER,ITALY,20,True,FEMALE,False,False,...,ACK,False,False,False,False,False,True,PAT_414_822_420.png,True,False
2287,PAT_754,False,False,ITALY,GERMANY,75,False,MALE,True,False,...,MEL,False,True,False,False,False,False,PAT_754_1429_380.png,True,True
2289,PAT_386,True,False,POMERANIA,POMERANIA,66,False,MALE,True,False,...,ACK,True,False,True,False,True,True,PAT_386_785_536.png,True,False

In [119]:
df = df.drop("diagnostic", axis="columns")

## Gender Binary Encoding

In [120]:
df["gender"]

1       FEMALE
4         MALE
6       FEMALE
7       FEMALE
9       FEMALE
         ...
2275      MALE
2284    FEMALE
2286    FEMALE
2287      MALE
2289      MALE
Name: gender, Length: 773, dtype: category
Categories (2, object): ['FEMALE', 'MALE']

In [121]:
df["gender"] = df["gender"].replace({"FEMALE": True, "MALE": False})
df["gender"] = df["gender"].astype("boolean")
df

/var/folders/sp/kjzzm68x2djdfrnp736n59bm0000gn/T/ipykernel_71980/1453782686.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["gender"] = df["gender"].replace({"FEMALE": True, "MALE": False})
/var/folders/sp/kjzzm68x2djdfrnp736n59bm0000gn/T/ipykernel_71980/1453782686.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df["gender"] = df["gender"].replace({"FEMALE": True, "MALE": False})

,patient_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,...,diameter_2,itch,grew,hurt,changed,bleed,elevation,img_id,biopsed,malignant
1,PAT_46,False,False,POMERANIA,POMERANIA,55,False,True,True,True,...,5.0,True,True,False,True,True,True,PAT_46_881_939.png,True,True
4,PAT_684,False,True,POMERANIA,POMERANIA,79,False,False,True,False,...,5.0,True,True,False,False,True,True,PAT_684_1302_588.png,True,True
6,PAT_778,False,True,GERMANY,ITALY,52,False,True,False,True,...,10.0,False,True,False,True,True,True,PAT_778_1471_835.png,True,True
7,PAT_117,False,False,POMERANIA,POMERANIA,74,True,True,False,False,...,10.0,True,True,True,False,True,True,PAT_117_179_983.png,True,True
9,PAT_705,False,True,GERMANY,GERMANY,58,True,True,True,True,...,7.0,False,True,False,False,False,False,PAT_705_4015_413.png,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,PAT_190,False,False,POMERANIA,POMERANIA,61,True,False,False,True,...,9.0,True,True,True,False,True,False,PAT_190_291_366.png,True,True
2284,PAT_498,False,True,POMERANIA,POMERANIA,60,True,True,True,False,...,2.0,False,False,False,False,False,False,PAT_498_944_488.png,True,False
2286,PAT_414,False,False,OTHER,ITALY,20,True,True,False,False,...,2.0,False,False,False,False,False,True,PAT_414_822_420.png,True,False
2287,PAT_754,False,False,ITALY,GERMANY,75,False,False,True,False,...,34.0,False,True,False,False,False,False,PAT_754_1429_380.png,True,True
2289,PAT_386,True,False,POMERANIA,POMERANIA,66,False,False,True,False,...,15.0,True,False,True,False,True,True,PAT_386_785_536.png,True,False

## One Hot Encode the Backgrounds

In [122]:
backgrounds = df["background_father"].unique()
for b in backgrounds:
    print(b)

POMERANIA
GERMANY
BRAZIL
NETHERLANDS
ITALY
POLAND
PORTUGAL
OTHER
BRASIL
AUSTRIA
ISRAEL

### Brazil is mispelled sometimes

In [123]:
df["background_father"] = df["background_father"].replace("BRASIL", "BRAZIL")
backgrounds = df["background_father"].unique()
for b in backgrounds:
    print(b)

POMERANIA
GERMANY
BRAZIL
NETHERLANDS
ITALY
POLAND
PORTUGAL
OTHER
AUSTRIA
ISRAEL

/var/folders/sp/kjzzm68x2djdfrnp736n59bm0000gn/T/ipykernel_71980/1493946901.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  df["background_father"] = df["background_father"].replace("BRASIL", "BRAZIL")

In [124]:
dummies = pd.get_dummies(df["background_father"], prefix="BG_FATHER")
dummies

,BG_FATHER_AUSTRIA,BG_FATHER_BRAZIL,BG_FATHER_CZECH,BG_FATHER_GERMANY,BG_FATHER_ISRAEL,BG_FATHER_ITALY,BG_FATHER_NETHERLANDS,BG_FATHER_POLAND,BG_FATHER_POMERANIA,BG_FATHER_PORTUGAL,BG_FATHER_SPAIN,BG_FATHER_OTHER
1,False,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False
6,False,False,False,True,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,True,False,False,False
9,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
2275,False,False,False,False,False,False,False,False,True,False,False,False
2284,False,False,False,False,False,False,False,False,True,False,False,False
2286,False,False,False,False,False,False,False,False,False,False,False,True
2287,False,False,False,False,False,True,False,False,False,False,False,False
2289,False,False,False,False,False,False,False,False,True,False,False,False

In [125]:
df = pd.concat([df, dummies], axis=1)
df

,patient_id,smoke,drink,background_father,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,...,BG_FATHER_CZECH,BG_FATHER_GERMANY,BG_FATHER_ISRAEL,BG_FATHER_ITALY,BG_FATHER_NETHERLANDS,BG_FATHER_POLAND,BG_FATHER_POMERANIA,BG_FATHER_PORTUGAL,BG_FATHER_SPAIN,BG_FATHER_OTHER
1,PAT_46,False,False,POMERANIA,POMERANIA,55,False,True,True,True,...,False,False,False,False,False,False,True,False,False,False
4,PAT_684,False,True,POMERANIA,POMERANIA,79,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
6,PAT_778,False,True,GERMANY,ITALY,52,False,True,False,True,...,False,True,False,False,False,False,False,False,False,False
7,PAT_117,False,False,POMERANIA,POMERANIA,74,True,True,False,False,...,False,False,False,False,False,False,True,False,False,False
9,PAT_705,False,True,GERMANY,GERMANY,58,True,True,True,True,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,PAT_190,False,False,POMERANIA,POMERANIA,61,True,False,False,True,...,False,False,False,False,False,False,True,False,False,False
2284,PAT_498,False,True,POMERANIA,POMERANIA,60,True,True,True,False,...,False,False,False,False,False,False,True,False,False,False
2286,PAT_414,False,False,OTHER,ITALY,20,True,True,False,False,...,False,False,False,False,False,False,False,False,False,True
2287,PAT_754,False,False,ITALY,GERMANY,75,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
2289,PAT_386,True,False,POMERANIA,POMERANIA,66,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False

In [126]:
df = df.drop("background_father", axis="columns")
df

,patient_id,smoke,drink,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,...,BG_FATHER_CZECH,BG_FATHER_GERMANY,BG_FATHER_ISRAEL,BG_FATHER_ITALY,BG_FATHER_NETHERLANDS,BG_FATHER_POLAND,BG_FATHER_POMERANIA,BG_FATHER_PORTUGAL,BG_FATHER_SPAIN,BG_FATHER_OTHER
1,PAT_46,False,False,POMERANIA,55,False,True,True,True,True,...,False,False,False,False,False,False,True,False,False,False
4,PAT_684,False,True,POMERANIA,79,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
6,PAT_778,False,True,ITALY,52,False,True,False,True,True,...,False,True,False,False,False,False,False,False,False,False
7,PAT_117,False,False,POMERANIA,74,True,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
9,PAT_705,False,True,GERMANY,58,True,True,True,True,True,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,PAT_190,False,False,POMERANIA,61,True,False,False,True,True,...,False,False,False,False,False,False,True,False,False,False
2284,PAT_498,False,True,POMERANIA,60,True,True,True,False,False,...,False,False,False,False,False,False,True,False,False,False
2286,PAT_414,False,False,ITALY,20,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2287,PAT_754,False,False,GERMANY,75,False,False,True,False,True,...,False,False,False,True,False,False,False,False,False,False
2289,PAT_386,True,False,POMERANIA,66,False,False,True,False,True,...,False,False,False,False,False,False,True,False,False,False

In [127]:
backgrounds = df["background_mother"].unique()
for b in backgrounds:
    print(b)

POMERANIA
ITALY
GERMANY
BRAZIL
OTHER
POLAND
NORWAY
PORTUGAL
NETHERLANDS
FRANCE
SPAIN

In [128]:
dummies = pd.get_dummies(df["background_mother"], prefix="BG_MOTHER")
dummies

,BG_MOTHER_BRAZIL,BG_MOTHER_FRANCE,BG_MOTHER_GERMANY,BG_MOTHER_ITALY,BG_MOTHER_NETHERLANDS,BG_MOTHER_NORWAY,BG_MOTHER_POLAND,BG_MOTHER_POMERANIA,BG_MOTHER_PORTUGAL,BG_MOTHER_SPAIN,BG_MOTHER_OTHER
1,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,True,False,False,False
6,False,False,False,True,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,True,False,False,False
9,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
2275,False,False,False,False,False,False,False,True,False,False,False
2284,False,False,False,False,False,False,False,True,False,False,False
2286,False,False,False,True,False,False,False,False,False,False,False
2287,False,False,True,False,False,False,False,False,False,False,False
2289,False,False,False,False,False,False,False,True,False,False,False

In [129]:
df = pd.concat([df, dummies], axis=1)
df

,patient_id,smoke,drink,background_mother,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,...,BG_MOTHER_FRANCE,BG_MOTHER_GERMANY,BG_MOTHER_ITALY,BG_MOTHER_NETHERLANDS,BG_MOTHER_NORWAY,BG_MOTHER_POLAND,BG_MOTHER_POMERANIA,BG_MOTHER_PORTUGAL,BG_MOTHER_SPAIN,BG_MOTHER_OTHER
1,PAT_46,False,False,POMERANIA,55,False,True,True,True,True,...,False,False,False,False,False,False,True,False,False,False
4,PAT_684,False,True,POMERANIA,79,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,False
6,PAT_778,False,True,ITALY,52,False,True,False,True,True,...,False,False,True,False,False,False,False,False,False,False
7,PAT_117,False,False,POMERANIA,74,True,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
9,PAT_705,False,True,GERMANY,58,True,True,True,True,True,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,PAT_190,False,False,POMERANIA,61,True,False,False,True,True,...,False,False,False,False,False,False,True,False,False,False
2284,PAT_498,False,True,POMERANIA,60,True,True,True,False,False,...,False,False,False,False,False,False,True,False,False,False
2286,PAT_414,False,False,ITALY,20,True,True,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2287,PAT_754,False,False,GERMANY,75,False,False,True,False,True,...,False,True,False,False,False,False,False,False,False,False
2289,PAT_386,True,False,POMERANIA,66,False,False,True,False,True,...,False,False,False,False,False,False,True,False,False,False

In [130]:
df = df.drop("background_mother", axis="columns")
df

,patient_id,smoke,drink,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,has_sewage_system,...,BG_MOTHER_FRANCE,BG_MOTHER_GERMANY,BG_MOTHER_ITALY,BG_MOTHER_NETHERLANDS,BG_MOTHER_NORWAY,BG_MOTHER_POLAND,BG_MOTHER_POMERANIA,BG_MOTHER_PORTUGAL,BG_MOTHER_SPAIN,BG_MOTHER_OTHER
1,PAT_46,False,False,55,False,True,True,True,True,True,...,False,False,False,False,False,False,True,False,False,False
4,PAT_684,False,True,79,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
6,PAT_778,False,True,52,False,True,False,True,True,True,...,False,False,True,False,False,False,False,False,False,False
7,PAT_117,False,False,74,True,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
9,PAT_705,False,True,58,True,True,True,True,True,True,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,PAT_190,False,False,61,True,False,False,True,True,False,...,False,False,False,False,False,False,True,False,False,False
2284,PAT_498,False,True,60,True,True,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False
2286,PAT_414,False,False,20,True,True,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2287,PAT_754,False,False,75,False,False,True,False,True,True,...,False,True,False,False,False,False,False,False,False,False
2289,PAT_386,True,False,66,False,False,True,False,True,True,...,False,False,False,False,False,False,True,False,False,False

## One Hot Encode the Region

In [131]:
regions = df["region"].unique()
for r in regions:
    print(r)

NECK
FOREARM
FACE
CHEST
THIGH
NOSE
BACK
ARM
HAND
EAR
FOOT
ABDOMEN
LIP
SCALP

In [132]:
dummies = pd.get_dummies(df["region"], prefix="REGION")
dummies

,REGION_ABDOMEN,REGION_ARM,REGION_BACK,REGION_CHEST,REGION_EAR,REGION_FACE,REGION_FOOT,REGION_FOREARM,REGION_HAND,REGION_LIP,REGION_NECK,REGION_NOSE,REGION_SCALP,REGION_THIGH
1,False,False,False,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,True,False,False,False,False,False,False
6,False,False,False,False,False,True,False,False,False,False,False,False,False,False
7,False,False,False,False,False,True,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2284,False,False,False,False,False,True,False,False,False,False,False,False,False,False
2286,False,False,True,False,False,False,False,False,False,False,False,False,False,False
2287,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2289,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [133]:
df = pd.concat([df, dummies], axis=1)
df

,patient_id,smoke,drink,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,has_sewage_system,...,REGION_EAR,REGION_FACE,REGION_FOOT,REGION_FOREARM,REGION_HAND,REGION_LIP,REGION_NECK,REGION_NOSE,REGION_SCALP,REGION_THIGH
1,PAT_46,False,False,55,False,True,True,True,True,True,...,False,False,False,False,False,False,True,False,False,False
4,PAT_684,False,True,79,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
6,PAT_778,False,True,52,False,True,False,True,True,True,...,False,True,False,False,False,False,False,False,False,False
7,PAT_117,False,False,74,True,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
9,PAT_705,False,True,58,True,True,True,True,True,True,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,PAT_190,False,False,61,True,False,False,True,True,False,...,False,False,False,True,False,False,False,False,False,False
2284,PAT_498,False,True,60,True,True,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
2286,PAT_414,False,False,20,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2287,PAT_754,False,False,75,False,False,True,False,True,True,...,False,False,False,True,False,False,False,False,False,False
2289,PAT_386,True,False,66,False,False,True,False,True,True,...,True,False,False,False,False,False,False,False,False,False

In [134]:
df = df.drop("region", axis="columns")
df

,patient_id,smoke,drink,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,has_sewage_system,...,REGION_EAR,REGION_FACE,REGION_FOOT,REGION_FOREARM,REGION_HAND,REGION_LIP,REGION_NECK,REGION_NOSE,REGION_SCALP,REGION_THIGH
1,PAT_46,False,False,55,False,True,True,True,True,True,...,False,False,False,False,False,False,True,False,False,False
4,PAT_684,False,True,79,False,False,True,False,False,False,...,False,False,False,True,False,False,False,False,False,False
6,PAT_778,False,True,52,False,True,False,True,True,True,...,False,True,False,False,False,False,False,False,False,False
7,PAT_117,False,False,74,True,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
9,PAT_705,False,True,58,True,True,True,True,True,True,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,PAT_190,False,False,61,True,False,False,True,True,False,...,False,False,False,True,False,False,False,False,False,False
2284,PAT_498,False,True,60,True,True,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
2286,PAT_414,False,False,20,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2287,PAT_754,False,False,75,False,False,True,False,True,True,...,False,False,False,True,False,False,False,False,False,False
2289,PAT_386,True,False,66,False,False,True,False,True,True,...,True,False,False,False,False,False,False,False,False,False

## Remove unnecesary features

In [135]:
df.describe(include="all")

,patient_id,smoke,drink,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,has_sewage_system,...,REGION_EAR,REGION_FACE,REGION_FOOT,REGION_FOREARM,REGION_HAND,REGION_LIP,REGION_NECK,REGION_NOSE,REGION_SCALP,REGION_THIGH
count,773,773,773,773.000000,773,773,773,773,773,773,...,773,773,773,773,773,773,773,773,773,773
unique,539,2,2,NaN,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
top,PAT_645,False,False,NaN,False,True,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
freq,8,674,587,NaN,454,396,420,419,454,411,...,743,574,768,662,729,763,740,701,770,746
mean,NaN,NaN,NaN,63.932730,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,14.101616,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,14.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,64.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,74.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,94.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [136]:
df.columns

Index(['patient_id', 'smoke', 'drink', 'age', 'pesticide', 'gender',
       'skin_cancer_history', 'cancer_history', 'has_piped_water',
       'has_sewage_system', 'fitspatrick', 'diameter_1', 'diameter_2', 'itch',
       'grew', 'hurt', 'changed', 'bleed', 'elevation', 'img_id', 'biopsed',
       'malignant', 'BG_FATHER_AUSTRIA', 'BG_FATHER_BRAZIL', 'BG_FATHER_CZECH',
       'BG_FATHER_GERMANY', 'BG_FATHER_ISRAEL', 'BG_FATHER_ITALY',
       'BG_FATHER_NETHERLANDS', 'BG_FATHER_POLAND', 'BG_FATHER_POMERANIA',
       'BG_FATHER_PORTUGAL', 'BG_FATHER_SPAIN', 'BG_FATHER_OTHER',
       'BG_MOTHER_BRAZIL', 'BG_MOTHER_FRANCE', 'BG_MOTHER_GERMANY',
       'BG_MOTHER_ITALY', 'BG_MOTHER_NETHERLANDS', 'BG_MOTHER_NORWAY',
       'BG_MOTHER_POLAND', 'BG_MOTHER_POMERANIA', 'BG_MOTHER_PORTUGAL',
       'BG_MOTHER_SPAIN', 'BG_MOTHER_OTHER', 'REGION_ABDOMEN', 'REGION_ARM',
       'REGION_BACK', 'REGION_CHEST', 'REGION_EAR', 'REGION_FACE',
       'REGION_FOOT', 'REGION_FOREARM', 'REGION_HAND', 'REGION_LIP',
       'REGION_NECK', 'REGION_NOSE', 'REGION_SCALP', 'REGION_THIGH'],
      dtype='object')

In [137]:
df = df.drop("patient_id", axis="columns")
df

,smoke,drink,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,has_sewage_system,fitspatrick,...,REGION_EAR,REGION_FACE,REGION_FOOT,REGION_FOREARM,REGION_HAND,REGION_LIP,REGION_NECK,REGION_NOSE,REGION_SCALP,REGION_THIGH
1,False,False,55,False,True,True,True,True,True,3.0,...,False,False,False,False,False,False,True,False,False,False
4,False,True,79,False,False,True,False,False,False,1.0,...,False,False,False,True,False,False,False,False,False,False
6,False,True,52,False,True,False,True,True,True,3.0,...,False,True,False,False,False,False,False,False,False,False
7,False,False,74,True,True,False,False,False,False,1.0,...,False,True,False,False,False,False,False,False,False,False
9,False,True,58,True,True,True,True,True,True,1.0,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,False,False,61,True,False,False,True,True,False,2.0,...,False,False,False,True,False,False,False,False,False,False
2284,False,True,60,True,True,True,False,False,False,2.0,...,False,True,False,False,False,False,False,False,False,False
2286,False,False,20,True,True,False,False,False,False,4.0,...,False,False,False,False,False,False,False,False,False,False
2287,False,False,75,False,False,True,False,True,True,2.0,...,False,False,False,True,False,False,False,False,False,False
2289,True,False,66,False,False,True,False,True,True,2.0,...,True,False,False,False,False,False,False,False,False,False

In [138]:
df = df.drop("img_id", axis="columns")
df

,smoke,drink,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,has_sewage_system,fitspatrick,...,REGION_EAR,REGION_FACE,REGION_FOOT,REGION_FOREARM,REGION_HAND,REGION_LIP,REGION_NECK,REGION_NOSE,REGION_SCALP,REGION_THIGH
1,False,False,55,False,True,True,True,True,True,3.0,...,False,False,False,False,False,False,True,False,False,False
4,False,True,79,False,False,True,False,False,False,1.0,...,False,False,False,True,False,False,False,False,False,False
6,False,True,52,False,True,False,True,True,True,3.0,...,False,True,False,False,False,False,False,False,False,False
7,False,False,74,True,True,False,False,False,False,1.0,...,False,True,False,False,False,False,False,False,False,False
9,False,True,58,True,True,True,True,True,True,1.0,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,False,False,61,True,False,False,True,True,False,2.0,...,False,False,False,True,False,False,False,False,False,False
2284,False,True,60,True,True,True,False,False,False,2.0,...,False,True,False,False,False,False,False,False,False,False
2286,False,False,20,True,True,False,False,False,False,4.0,...,False,False,False,False,False,False,False,False,False,False
2287,False,False,75,False,False,True,False,True,True,2.0,...,False,False,False,True,False,False,False,False,False,False
2289,True,False,66,False,False,True,False,True,True,2.0,...,True,False,False,False,False,False,False,False,False,False

## Make all features numerical

In [139]:
df.select_dtypes(include="boolean").columns

Index(['smoke', 'drink', 'pesticide', 'gender', 'skin_cancer_history',
       'cancer_history', 'has_piped_water', 'has_sewage_system', 'itch',
       'grew', 'hurt', 'changed', 'bleed', 'elevation', 'biopsed', 'malignant',
       'BG_FATHER_AUSTRIA', 'BG_FATHER_BRAZIL', 'BG_FATHER_CZECH',
       'BG_FATHER_GERMANY', 'BG_FATHER_ISRAEL', 'BG_FATHER_ITALY',
       'BG_FATHER_NETHERLANDS', 'BG_FATHER_POLAND', 'BG_FATHER_POMERANIA',
       'BG_FATHER_PORTUGAL', 'BG_FATHER_SPAIN', 'BG_FATHER_OTHER',
       'BG_MOTHER_BRAZIL', 'BG_MOTHER_FRANCE', 'BG_MOTHER_GERMANY',
       'BG_MOTHER_ITALY', 'BG_MOTHER_NETHERLANDS', 'BG_MOTHER_NORWAY',
       'BG_MOTHER_POLAND', 'BG_MOTHER_POMERANIA', 'BG_MOTHER_PORTUGAL',
       'BG_MOTHER_SPAIN', 'BG_MOTHER_OTHER', 'REGION_ABDOMEN', 'REGION_ARM',
       'REGION_BACK', 'REGION_CHEST', 'REGION_EAR', 'REGION_FACE',
       'REGION_FOOT', 'REGION_FOREARM', 'REGION_HAND', 'REGION_LIP',
       'REGION_NECK', 'REGION_NOSE', 'REGION_SCALP', 'REGION_THIGH'],
      dtype='object')

In [140]:
boolean_cols = df.select_dtypes(include="boolean").columns
df[boolean_cols] = df[boolean_cols].astype(int)
df

,smoke,drink,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,has_sewage_system,fitspatrick,...,REGION_EAR,REGION_FACE,REGION_FOOT,REGION_FOREARM,REGION_HAND,REGION_LIP,REGION_NECK,REGION_NOSE,REGION_SCALP,REGION_THIGH
1,0,0,55,0,1,1,1,1,1,3.0,...,0,0,0,0,0,0,1,0,0,0
4,0,1,79,0,0,1,0,0,0,1.0,...,0,0,0,1,0,0,0,0,0,0
6,0,1,52,0,1,0,1,1,1,3.0,...,0,1,0,0,0,0,0,0,0,0
7,0,0,74,1,1,0,0,0,0,1.0,...,0,1,0,0,0,0,0,0,0,0
9,0,1,58,1,1,1,1,1,1,1.0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2275,0,0,61,1,0,0,1,1,0,2.0,...,0,0,0,1,0,0,0,0,0,0
2284,0,1,60,1,1,1,0,0,0,2.0,...,0,1,0,0,0,0,0,0,0,0
2286,0,0,20,1,1,0,0,0,0,4.0,...,0,0,0,0,0,0,0,0,0,0
2287,0,0,75,0,0,1,0,1,1,2.0,...,0,0,0,1,0,0,0,0,0,0
2289,1,0,66,0,0,1,0,1,1,2.0,...,1,0,0,0,0,0,0,0,0,0

In [141]:
df.describe()

,smoke,drink,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,has_sewage_system,fitspatrick,...,REGION_EAR,REGION_FACE,REGION_FOOT,REGION_FOREARM,REGION_HAND,REGION_LIP,REGION_NECK,REGION_NOSE,REGION_SCALP,REGION_THIGH
count,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,...,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000
mean,0.128072,0.240621,63.932730,0.412678,0.512290,0.456662,0.542044,0.587322,0.531695,2.262613,...,0.038810,0.257439,0.006468,0.143596,0.056921,0.012937,0.042691,0.093144,0.003881,0.034929
std,0.334387,0.427737,14.101616,0.492635,0.500173,0.498441,0.498552,0.492635,0.499318,0.758108,...,0.193267,0.437506,0.080217,0.350907,0.231842,0.113074,0.202290,0.290822,0.062217,0.183719
min,0.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,55.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,64.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,2.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,74.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,94.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## Normalize the data

In [142]:
unnormalized = [c for c in df.columns if max(df[c]) > 1]
unnormalized

['age', 'fitspatrick', 'diameter_1', 'diameter_2']

In [143]:
df[["age", "fitspatrick", "diameter_1", "diameter_2"]]

      age  fitspatrick  diameter_1  diameter_2
1      55          3.0         6.0         5.0
4      79          1.0         5.0         5.0
6      52          3.0        15.0        10.0
7      74          1.0        15.0        10.0
9      58          1.0         9.0         7.0
...   ...          ...         ...         ...
2275   61          2.0        15.0         9.0
2284   60          2.0         4.0         2.0
2286   20          4.0         4.0         2.0
2287   75          2.0        40.0        34.0
2289   66          2.0        20.0        15.0

[773 rows x 4 columns]

In [144]:
scaler = preprocessing.MinMaxScaler()

In [145]:
df["age"]

1       55
4       79
6       52
7       74
9       58
        ..
2275    61
2284    60
2286    20
2287    75
2289    66
Name: age, Length: 773, dtype: int64

In [146]:
df["age"] = scaler.fit_transform([[a] for a in df["age"]])
df["age"]

1       0.5125
4       0.8125
6       0.4750
7       0.7500
9       0.5500
         ...
2275    0.5875
2284    0.5750
2286    0.0750
2287    0.7625
2289    0.6500
Name: age, Length: 773, dtype: float64

In [147]:
df["fitspatrick"].unique()

array([3., 1., 2., 4., 5., 6.])

In [148]:
df["fitspatrick"] = scaler.fit_transform([[f] for f in df["fitspatrick"]])
df["fitspatrick"]

1       0.4
4       0.0
6       0.4
7       0.0
9       0.0
       ...
2275    0.2
2284    0.2
2286    0.6
2287    0.2
2289    0.2
Name: fitspatrick, Length: 773, dtype: float64

In [149]:
df["diameter_1"]

1        6.0
4        5.0
6       15.0
7       15.0
9        9.0
        ...
2275    15.0
2284     4.0
2286     4.0
2287    40.0
2289    20.0
Name: diameter_1, Length: 773, dtype: float64

In [150]:
df["diameter_1"] = scaler.fit_transform([[d] for d in df["diameter_1"]])
df["diameter_1"]

1       0.085714
4       0.071429
6       0.214286
7       0.214286
9       0.128571
          ...
2275    0.214286
2284    0.057143
2286    0.057143
2287    0.571429
2289    0.285714
Name: diameter_1, Length: 773, dtype: float64

In [151]:
df["diameter_2"]

1        5.0
4        5.0
6       10.0
7       10.0
9        7.0
        ...
2275     9.0
2284     2.0
2286     2.0
2287    34.0
2289    15.0
Name: diameter_2, Length: 773, dtype: float64

In [152]:
df["diameter_2"] = scaler.fit_transform([[d] for d in df["diameter_2"]])
df["diameter_2"]

1       0.083333
4       0.083333
6       0.166667
7       0.166667
9       0.116667
          ...
2275    0.150000
2284    0.033333
2286    0.033333
2287    0.566667
2289    0.250000
Name: diameter_2, Length: 773, dtype: float64

In [153]:
df.describe()

,smoke,drink,age,pesticide,gender,skin_cancer_history,cancer_history,has_piped_water,has_sewage_system,fitspatrick,...,REGION_EAR,REGION_FACE,REGION_FOOT,REGION_FOREARM,REGION_HAND,REGION_LIP,REGION_NECK,REGION_NOSE,REGION_SCALP,REGION_THIGH
count,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,...,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000
mean,0.128072,0.240621,0.624159,0.412678,0.512290,0.456662,0.542044,0.587322,0.531695,0.252523,...,0.038810,0.257439,0.006468,0.143596,0.056921,0.012937,0.042691,0.093144,0.003881,0.034929
std,0.334387,0.427737,0.176270,0.492635,0.500173,0.498441,0.498552,0.492635,0.499318,0.151622,...,0.193267,0.437506,0.080217,0.350907,0.231842,0.113074,0.202290,0.290822,0.062217,0.183719
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.512500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.200000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.625000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.200000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.750000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.400000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000